#!/usr/bin/env python3
"""Builds the app's JLPT N5 assets from the curated word list below.

Run from the repo root:

    python3 scripts/build_n5_data.py

Writes three files, mirroring how the deck is split at runtime (see
lib/data/n5_repository.dart):

  assets/data/n5.json            - the word list itself
  assets/data/n5_sentences.json  - one example sentence per word
  assets/data/n5_kanji_info.json - stroke count + on/kun readings, for the
                                   single-kanji words only

The split is deliberate: the study card reads all three, but keeping them
apart keeps each asset small (the same reason the Mandarin app this design
came from split its HSK1 asset - a single large JSON stalls
`rootBundle.loadString` under flutter_test's mocked asset channel).

The word list is hand-curated core N5 vocabulary - the aim is a usable
starter deck with a natural, grammatical example sentence per entry, not an
exhaustive reproduction of any single published N5 list (there is no
official one).
"""

import json
import os

# (japanese, kana, romaji, english, part of speech,
#  sentence, sentence kana, sentence english)
WORDS = [
    ("私", "わたし", "watashi", "I; me", "pronoun",
     "私は学生です。", "わたしはがくせいです。", "I am a student."),
    ("あなた", "あなた", "anata", "you", "pronoun",
     "あなたの名前は何ですか。", "あなたのなまえはなんですか。", "What is your name?"),
    ("人", "ひと", "hito", "person", "noun",
     "あの人は先生です。", "あのひとはせんせいです。", "That person is a teacher."),
    ("友達", "ともだち", "tomodachi", "friend", "noun",
     "友達と映画を見ます。", "ともだちとえいがをみます。", "I watch a movie with a friend."),
    ("家族", "かぞく", "kazoku", "family", "noun",
     "家族は四人です。", "かぞくはよにんです。", "There are four people in my family."),
    ("母", "はは", "haha", "(my) mother", "noun",
     "母は料理が上手です。", "ははは りょうりが じょうずです。", "My mother is good at cooking."),
    ("父", "ちち", "chichi", "(my) father", "noun",
     "父は会社員です。", "ちちはかいしゃいんです。", "My father is a company employee."),
    ("先生", "せんせい", "sensei", "teacher", "noun",
     "先生に質問します。", "せんせいにしつもんします。", "I ask the teacher a question."),
    ("学生", "がくせい", "gakusei", "student", "noun",
     "私は大学の学生です。", "わたしはだいがくのがくせいです。", "I am a university student."),
    ("学校", "がっこう", "gakkou", "school", "noun",
     "学校は駅の近くです。", "がっこうはえきのちかくです。", "The school is near the station."),
    ("大学", "だいがく", "daigaku", "university", "noun",
     "兄は大学で勉強しています。", "あにはだいがくでべんきょうしています。",
     "My older brother studies at university."),
    ("会社", "かいしゃ", "kaisha", "company", "noun",
     "会社まで電車で行きます。", "かいしゃまででんしゃでいきます。", "I go to the company by train."),
    ("仕事", "しごと", "shigoto", "work; job", "noun",
     "今日は仕事が多いです。", "きょうはしごとがおおいです。", "There is a lot of work today."),
    ("名前", "なまえ", "namae", "name", "noun",
     "ここに名前を書いてください。", "ここになまえをかいてください。", "Please write your name here."),
    ("日本", "にほん", "nihon", "Japan", "noun",
     "日本は島の国です。", "にほんはしまのくにです。", "Japan is an island country."),
    ("日本語", "にほんご", "nihongo", "Japanese (language)", "noun",
     "日本語を毎日勉強します。", "にほんごをまいにちべんきょうします。", "I study Japanese every day."),
    ("英語", "えいご", "eigo", "English (language)", "noun",
     "姉は英語が話せます。", "あねはえいごがはなせます。", "My older sister can speak English."),
    ("言葉", "ことば", "kotoba", "word; language", "noun",
     "この言葉の意味は何ですか。", "このことばのいみはなんですか。", "What does this word mean?"),
    ("本", "ほん", "hon", "book", "noun",
     "図書館で本を借ります。", "としょかんでほんをかります。", "I borrow a book at the library."),
    ("新聞", "しんぶん", "shinbun", "newspaper", "noun",
     "朝、新聞を読みます。", "あさ、しんぶんをよみます。", "I read the newspaper in the morning."),
    ("手紙", "てがみ", "tegami", "letter", "noun",
     "友達に手紙を書きました。", "ともだちにてがみをかきました。", "I wrote a letter to my friend."),
    ("電話", "でんわ", "denwa", "telephone; phone call", "noun",
     "後で電話します。", "あとででんわします。", "I will call you later."),
    ("時間", "じかん", "jikan", "time; hour", "noun",
     "今日は時間がありません。", "きょうはじかんがありません。", "I don't have time today."),
    ("今日", "きょう", "kyou", "today", "noun",
     "今日は暑いですね。", "きょうはあついですね。", "It's hot today, isn't it."),
    ("明日", "あした", "ashita", "tomorrow", "noun",
     "明日、京都へ行きます。", "あした、きょうとへいきます。", "I'm going to Kyoto tomorrow."),
    ("昨日", "きのう", "kinou", "yesterday", "noun",
     "昨日は雨でした。", "きのうはあめでした。", "It rained yesterday."),
    ("朝", "あさ", "asa", "morning", "noun",
     "朝ご飯を食べます。", "あさごはんをたべます。", "I eat breakfast."),
    ("昼", "ひる", "hiru", "noon; daytime", "noun",
     "昼はパンを食べます。", "ひるはパンをたべます。", "I eat bread at midday."),
    ("夜", "よる", "yoru", "night", "noun",
     "夜は静かです。", "よるはしずかです。", "It is quiet at night."),
    ("今", "いま", "ima", "now", "noun",
     "今、何時ですか。", "いま、なんじですか。", "What time is it now?"),
    ("毎日", "まいにち", "mainichi", "every day", "noun; adverb",
     "毎日、歩きます。", "まいにち、あるきます。", "I walk every day."),
    ("週末", "しゅうまつ", "shuumatsu", "weekend", "noun",
     "週末は家にいます。", "しゅうまつはいえにいます。", "I stay at home on the weekend."),
    ("年", "とし", "toshi", "year; age", "noun",
     "今年は忙しい年です。", "ことしはいそがしいとしです。", "This year is a busy year."),
    ("水", "みず", "mizu", "water", "noun",
     "水を一杯ください。", "みずをいっぱいください。", "A glass of water, please."),
    ("お茶", "おちゃ", "ocha", "tea", "noun",
     "お茶を飲みませんか。", "おちゃをのみませんか。", "Won't you have some tea?"),
    ("ご飯", "ごはん", "gohan", "cooked rice; meal", "noun",
     "ご飯はもうできましたか。", "ごはんはもうできましたか。", "Is the meal ready yet?"),
    ("肉", "にく", "niku", "meat", "noun",
     "肉より魚が好きです。", "にくよりさかながすきです。", "I like fish more than meat."),
    ("魚", "さかな", "sakana", "fish", "noun",
     "魚を焼きます。", "さかなをやきます。", "I grill fish."),
    ("野菜", "やさい", "yasai", "vegetable", "noun",
     "野菜をたくさん食べましょう。", "やさいをたくさんたべましょう。", "Let's eat a lot of vegetables."),
    ("果物", "くだもの", "kudamono", "fruit", "noun",
     "果物は体にいいです。", "くだものはからだにいいです。", "Fruit is good for you."),
    ("店", "みせ", "mise", "shop; store", "noun",
     "その店は八時に閉まります。", "そのみせははちじにしまります。", "That shop closes at eight."),
    ("駅", "えき", "eki", "station", "noun",
     "駅で友達を待ちます。", "えきでともだちをまちます。", "I wait for my friend at the station."),
    ("電車", "でんしゃ", "densha", "train", "noun",
     "電車が来ました。", "でんしゃがきました。", "The train has come."),
    ("車", "くるま", "kuruma", "car", "noun",
     "車で海へ行きます。", "くるまでうみへいきます。", "I go to the sea by car."),
    ("自転車", "じてんしゃ", "jitensha", "bicycle", "noun",
     "自転車で学校に通います。", "じてんしゃでがっこうにかよいます。", "I commute to school by bicycle."),
    ("家", "いえ", "ie", "house; home", "noun",
     "そろそろ家に帰ります。", "そろそろいえにかえります。", "I'm heading home soon."),
    ("部屋", "へや", "heya", "room", "noun",
     "部屋を掃除します。", "へやをそうじします。", "I clean the room."),
    ("町", "まち", "machi", "town", "noun",
     "この町は静かです。", "このまちはしずかです。", "This town is quiet."),
    ("国", "くに", "kuni", "country", "noun",
     "お国はどちらですか。", "おくにはどちらですか。", "Which country are you from?"),
    ("道", "みち", "michi", "road; way", "noun",
     "道を教えてください。", "みちをおしえてください。", "Please tell me the way."),
    ("空", "そら", "sora", "sky", "noun",
     "空が青いです。", "そらがあおいです。", "The sky is blue."),
    ("雨", "あめ", "ame", "rain", "noun",
     "明日は雨でしょう。", "あしたはあめでしょう。", "It will probably rain tomorrow."),
    ("雪", "ゆき", "yuki", "snow", "noun",
     "北海道は雪が多いです。", "ほっかいどうはゆきがおおいです。", "There is a lot of snow in Hokkaido."),
    ("風", "かぜ", "kaze", "wind", "noun",
     "今日は風が強いです。", "きょうはかぜがつよいです。", "The wind is strong today."),
    ("花", "はな", "hana", "flower", "noun",
     "庭に花が咲いています。", "にわにはながさいています。", "Flowers are blooming in the garden."),
    ("木", "き", "ki", "tree; wood", "noun",
     "大きい木の下で休みます。", "おおきいきのしたでやすみます。", "I rest under a big tree."),
    ("山", "やま", "yama", "mountain", "noun",
     "夏に山に登ります。", "なつにやまにのぼります。", "I climb mountains in summer."),
    ("川", "かわ", "kawa", "river", "noun",
     "川で泳いではいけません。", "かわでおよいではいけません。", "You must not swim in the river."),
    ("海", "うみ", "umi", "sea; ocean", "noun",
     "窓から海が見えます。", "まどからうみがみえます。", "I can see the sea from the window."),
    ("犬", "いぬ", "inu", "dog", "noun",
     "犬と散歩します。", "いぬとさんぽします。", "I take a walk with my dog."),
    ("猫", "ねこ", "neko", "cat", "noun",
     "猫が窓から入りました。", "ねこがまどからはいりました。", "The cat came in through the window."),
    ("食べる", "たべる", "taberu", "to eat", "ichidan verb",
     "毎朝パンを食べます。", "まいあさパンをたべます。", "I eat bread every morning."),
    ("飲む", "のむ", "nomu", "to drink", "godan verb",
     "水をたくさん飲みます。", "みずをたくさんのみます。", "I drink a lot of water."),
    ("行く", "いく", "iku", "to go", "godan verb",
     "明日、病院へ行きます。", "あした、びょういんへいきます。", "I'm going to the hospital tomorrow."),
    ("来る", "くる", "kuru", "to come", "irregular verb",
     "友達が家に来ます。", "ともだちがいえにきます。", "A friend is coming to my house."),
    ("帰る", "かえる", "kaeru", "to go home; to return", "godan verb",
     "六時に帰ります。", "ろくじにかえります。", "I'll head back at six."),
    ("見る", "みる", "miru", "to see; to watch", "ichidan verb",
     "テレビを見ています。", "テレビをみています。", "I am watching TV."),
    ("聞く", "きく", "kiku", "to listen; to ask", "godan verb",
     "音楽を聞きます。", "おんがくをききます。", "I listen to music."),
    ("話す", "はなす", "hanasu", "to speak; to talk", "godan verb",
     "日本語で話しましょう。", "にほんごではなしましょう。", "Let's talk in Japanese."),
    ("読む", "よむ", "yomu", "to read", "godan verb",
     "毎晩、本を読みます。", "まいばん、ほんをよみます。", "I read a book every night."),
    ("書く", "かく", "kaku", "to write", "godan verb",
     "ノートに漢字を書きます。", "ノートにかんじをかきます。", "I write kanji in my notebook."),
    ("買う", "かう", "kau", "to buy", "godan verb",
     "店でパンを買いました。", "みせでパンをかいました。", "I bought bread at the store."),
    ("する", "する", "suru", "to do", "irregular verb",
     "今日は何をしますか。", "きょうはなにをしますか。", "What will you do today?"),
    ("わかる", "わかる", "wakaru", "to understand", "godan verb",
     "意味がわかりません。", "いみがわかりません。", "I don't understand the meaning."),
    ("教える", "おしえる", "oshieru", "to teach; to tell", "ichidan verb",
     "電話番号を教えてください。", "でんわばんごうをおしえてください。", "Please tell me your phone number."),
    ("習う", "ならう", "narau", "to learn", "godan verb",
     "ピアノを習っています。", "ピアノをならっています。", "I am learning the piano."),
    ("勉強する", "べんきょうする", "benkyou suru", "to study", "irregular verb",
     "図書館で勉強します。", "としょかんでべんきょうします。", "I study at the library."),
    ("働く", "はたらく", "hataraku", "to work", "godan verb",
     "父は銀行で働いています。", "ちちはぎんこうではたらいています。", "My father works at a bank."),
    ("休む", "やすむ", "yasumu", "to rest; to take time off", "godan verb",
     "今日は仕事を休みます。", "きょうはしごとをやすみます。", "I'm taking the day off work today."),
    ("起きる", "おきる", "okiru", "to get up; to wake up", "ichidan verb",
     "毎朝六時に起きます。", "まいあさろくじにおきます。", "I get up at six every morning."),
    ("寝る", "ねる", "neru", "to sleep; to go to bed", "ichidan verb",
     "十一時に寝ます。", "じゅういちじにねます。", "I go to bed at eleven."),
    ("待つ", "まつ", "matsu", "to wait", "godan verb",
     "ここで待ってください。", "ここでまってください。", "Please wait here."),
    ("会う", "あう", "au", "to meet", "godan verb",
     "駅で友達に会いました。", "えきでともだちにあいました。", "I met a friend at the station."),
    ("作る", "つくる", "tsukuru", "to make", "godan verb",
     "母が夕飯を作ります。", "ははがゆうはんをつくります。", "My mother makes dinner."),
    ("使う", "つかう", "tsukau", "to use", "godan verb",
     "このペンを使ってもいいですか。", "このペンをつかってもいいですか。", "May I use this pen?"),
    ("歩く", "あるく", "aruku", "to walk", "godan verb",
     "駅まで歩きます。", "えきまであるきます。", "I walk to the station."),
    ("走る", "はしる", "hashiru", "to run", "godan verb",
     "公園を走ります。", "こうえんをはしります。", "I run in the park."),
    ("泳ぐ", "およぐ", "oyogu", "to swim", "godan verb",
     "夏は毎日泳ぎます。", "なつはまいにちおよぎます。", "I swim every day in summer."),
    ("立つ", "たつ", "tatsu", "to stand", "godan verb",
     "みなさん、立ってください。", "みなさん、たってください。", "Everyone, please stand up."),
    ("座る", "すわる", "suwaru", "to sit", "godan verb",
     "いすに座ってください。", "いすにすわってください。", "Please sit on the chair."),
    ("入る", "はいる", "hairu", "to enter", "godan verb",
     "部屋に入ってもいいですか。", "へやにはいってもいいですか。", "May I come into the room?"),
    ("出る", "でる", "deru", "to leave; to go out", "ichidan verb",
     "八時に家を出ます。", "はちじにいえをでます。", "I leave home at eight."),
    ("開ける", "あける", "akeru", "to open (something)", "ichidan verb",
     "窓を開けてください。", "まどをあけてください。", "Please open the window."),
    ("閉める", "しめる", "shimeru", "to close (something)", "ichidan verb",
     "寒いのでドアを閉めます。", "さむいのでドアをしめます。", "It's cold, so I'll close the door."),
    ("持つ", "もつ", "motsu", "to hold; to carry", "godan verb",
     "かばんを持ちましょうか。", "かばんをもちましょうか。", "Shall I carry your bag?"),
    ("貸す", "かす", "kasu", "to lend", "godan verb",
     "その本を貸してください。", "そのほんをかしてください。", "Please lend me that book."),
    ("借りる", "かりる", "kariru", "to borrow", "ichidan verb",
     "友達に傘を借りました。", "ともだちにかさをかりました。", "I borrowed an umbrella from a friend."),
    ("覚える", "おぼえる", "oboeru", "to memorize; to remember", "ichidan verb",
     "毎日、単語を覚えます。", "まいにち、たんごをおぼえます。", "I memorize vocabulary every day."),
    ("忘れる", "わすれる", "wasureru", "to forget", "ichidan verb",
     "電車に傘を忘れました。", "でんしゃにかさをわすれました。", "I left my umbrella on the train."),
    ("遊ぶ", "あそぶ", "asobu", "to play; to have fun", "godan verb",
     "公園で子どもが遊んでいます。", "こうえんでこどもがあそんでいます。",
     "Children are playing in the park."),
    ("大きい", "おおきい", "ookii", "big", "i-adjective",
     "庭に大きい犬がいます。", "にわにおおきいいぬがいます。", "There is a big dog in the garden."),
    ("小さい", "ちいさい", "chiisai", "small", "i-adjective",
     "小さい部屋に住んでいます。", "ちいさいへやにすんでいます。", "I live in a small room."),
    ("新しい", "あたらしい", "atarashii", "new", "i-adjective",
     "新しい靴を買いました。", "あたらしいくつをかいました。", "I bought new shoes."),
    ("古い", "ふるい", "furui", "old (of things)", "i-adjective",
     "この寺はとても古いです。", "このてらはとてもふるいです。", "This temple is very old."),
    ("高い", "たかい", "takai", "expensive; tall", "i-adjective",
     "この時計は高いです。", "このとけいはたかいです。", "This watch is expensive."),
    ("安い", "やすい", "yasui", "cheap", "i-adjective",
     "安い店を知っています。", "やすいみせをしっています。", "I know a cheap shop."),
    ("いい", "いい", "ii", "good", "i-adjective",
     "今日は天気がいいですね。", "きょうはてんきがいいですね。", "The weather is nice today, isn't it."),
    ("悪い", "わるい", "warui", "bad", "i-adjective",
     "今日は天気が悪いです。", "きょうはてんきがわるいです。", "The weather is bad today."),
    ("暑い", "あつい", "atsui", "hot (weather)", "i-adjective",
     "夏はとても暑いです。", "なつはとてもあついです。", "Summer is very hot."),
    ("寒い", "さむい", "samui", "cold (weather)", "i-adjective",
     "冬は寒いです。", "ふゆはさむいです。", "Winter is cold."),
    ("忙しい", "いそがしい", "isogashii", "busy", "i-adjective",
     "今週は忙しいです。", "こんしゅうはいそがしいです。", "I am busy this week."),
    ("楽しい", "たのしい", "tanoshii", "fun; enjoyable", "i-adjective",
     "旅行は楽しかったです。", "りょこうはたのしかったです。", "The trip was fun."),
    ("面白い", "おもしろい", "omoshiroi", "interesting; funny", "i-adjective",
     "この本は面白いです。", "このほんはおもしろいです。", "This book is interesting."),
    ("難しい", "むずかしい", "muzukashii", "difficult", "i-adjective",
     "漢字は難しいです。", "かんじはむずかしいです。", "Kanji is difficult."),
    ("簡単", "かんたん", "kantan", "easy; simple", "na-adjective",
     "この問題は簡単です。", "このもんだいはかんたんです。", "This question is easy."),
    ("静か", "しずか", "shizuka", "quiet", "na-adjective",
     "図書館は静かです。", "としょかんはしずかです。", "The library is quiet."),
    ("元気", "げんき", "genki", "healthy; energetic", "na-adjective",
     "お元気ですか。", "おげんきですか。", "How are you?"),
    ("好き", "すき", "suki", "liked; fond of", "na-adjective",
     "音楽が好きです。", "おんがくがすきです。", "I like music."),
    ("上手", "じょうず", "jouzu", "skillful; good at", "na-adjective",
     "姉は歌が上手です。", "あねはうたがじょうずです。", "My older sister is good at singing."),
    ("有名", "ゆうめい", "yuumei", "famous", "na-adjective",
     "この店は有名です。", "このみせはゆうめいです。", "This shop is famous."),
    ("きれい", "きれい", "kirei", "pretty; clean", "na-adjective",
     "部屋がきれいになりました。", "へやがきれいになりました。", "The room has become clean."),
    ("多い", "おおい", "ooi", "many; much", "i-adjective",
     "今日は人が多いですね。", "きょうはひとがおおいですね。", "There are a lot of people today."),
    ("少ない", "すくない", "sukunai", "few; little", "i-adjective",
     "今日は客が少ないです。", "きょうはきゃくがすくないです。", "There are few customers today."),
    ("近い", "ちかい", "chikai", "near", "i-adjective",
     "駅は家から近いです。", "えきはいえからちかいです。", "The station is near my house."),
    ("遠い", "とおい", "tooi", "far", "i-adjective",
     "学校は駅から遠いです。", "がっこうはえきからとおいです。", "The school is far from the station."),
    ("早い", "はやい", "hayai", "early", "i-adjective",
     "今日は早く起きました。", "きょうははやくおきました。", "I got up early today."),
    ("長い", "ながい", "nagai", "long", "i-adjective",
     "この川はとても長いです。", "このかわはとてもながいです。", "This river is very long."),
    ("短い", "みじかい", "mijikai", "short", "i-adjective",
     "髪を短くしました。", "かみをみじかくしました。", "I cut my hair short."),
    ("白い", "しろい", "shiroi", "white", "i-adjective",
     "白いシャツを着ています。", "しろいシャツをきています。", "I am wearing a white shirt."),
    ("赤い", "あかい", "akai", "red", "i-adjective",
     "赤いりんごを買います。", "あかいりんごをかいます。", "I'll buy red apples."),
    ("一つ", "ひとつ", "hitotsu", "one (thing)", "counter",
     "りんごを一つください。", "りんごをひとつください。", "One apple, please."),
    ("二つ", "ふたつ", "futatsu", "two (things)", "counter",
     "パンを二つ買いました。", "パンをふたつかいました。", "I bought two rolls of bread."),
    ("何", "なに", "nani", "what", "pronoun",
     "これは何ですか。", "これはなんですか。", "What is this?"),
    ("誰", "だれ", "dare", "who", "pronoun",
     "あの人は誰ですか。", "あのひとはだれですか。", "Who is that person?"),
    ("どこ", "どこ", "doko", "where", "pronoun",
     "トイレはどこですか。", "トイレはどこですか。", "Where is the toilet?"),
    ("いつ", "いつ", "itsu", "when", "adverb",
     "いつ日本へ来ましたか。", "いつにほんへきましたか。", "When did you come to Japan?"),
    ("どう", "どう", "dou", "how", "adverb",
     "味はどうですか。", "あじはどうですか。", "How does it taste?"),
    ("とても", "とても", "totemo", "very", "adverb",
     "この料理はとてもおいしいです。", "このりょうりはとてもおいしいです。", "This dish is very tasty."),
    ("少し", "すこし", "sukoshi", "a little", "adverb",
     "少し休みましょう。", "すこしやすみましょう。", "Let's rest a little."),
    ("たくさん", "たくさん", "takusan", "a lot; many", "adverb",
     "写真をたくさん撮りました。", "しゃしんをたくさんとりました。", "I took a lot of photos."),
    ("もう", "もう", "mou", "already", "adverb",
     "もう昼ご飯を食べました。", "もうひるごはんをたべました。", "I have already eaten lunch."),
    ("まだ", "まだ", "mada", "not yet; still", "adverb",
     "まだ宿題をしていません。", "まだしゅくだいをしていません。", "I haven't done my homework yet."),
    ("一緒に", "いっしょに", "issho ni", "together", "adverb",
     "一緒に行きましょう。", "いっしょにいきましょう。", "Let's go together."),
    ("ゆっくり", "ゆっくり", "yukkuri", "slowly", "adverb",
     "もっとゆっくり話してください。", "もっとゆっくりはなしてください。", "Please speak more slowly."),
    ("ありがとう", "ありがとう", "arigatou", "thank you", "expression",
     "手伝ってくれてありがとう。", "てつだってくれてありがとう。", "Thank you for helping me."),
    ("すみません", "すみません", "sumimasen", "excuse me; sorry", "expression",
     "すみません、道を教えてください。", "すみません、みちをおしえてください。",
     "Excuse me, please tell me the way."),
    ("お願いします", "おねがいします", "onegaishimasu", "please", "expression",
     "コーヒーをお願いします。", "コーヒーをおねがいします。", "Coffee, please."),
    ("おはよう", "おはよう", "ohayou", "good morning", "expression",
     "おはよう、今日も元気ですね。", "おはよう、きょうもげんきですね。",
     "Good morning - you're lively again today."),
    ("こんにちは", "こんにちは", "konnichiwa", "hello; good afternoon", "expression",
     "こんにちは、いい天気ですね。", "こんにちは、いいてんきですね。", "Hello - nice weather, isn't it."),
    ("さようなら", "さようなら", "sayounara", "goodbye", "expression",
     "さようなら、また明日。", "さようなら、またあした。", "Goodbye, see you tomorrow."),
]

# Single-kanji entries only: stroke count plus the readings that word uses
# most plainly. on readings are conventionally written in katakana, kun in
# hiragana; a "-" means the character has no common reading of that kind.
KANJI_INFO = {
    "私": (7, "シ", "わたし"),
    "人": (2, "ジン", "ひと"),
    "母": (5, "ボ", "はは"),
    "父": (4, "フ", "ちち"),
    "本": (5, "ホン", "もと"),
    "今": (4, "コン", "いま"),
    "年": (6, "ネン", "とし"),
    "朝": (12, "チョウ", "あさ"),
    "昼": (9, "チュウ", "ひる"),
    "夜": (8, "ヤ", "よる"),
    "水": (4, "スイ", "みず"),
    "肉": (6, "ニク", "-"),
    "魚": (11, "ギョ", "さかな"),
    "店": (8, "テン", "みせ"),
    "駅": (14, "エキ", "-"),
    "車": (7, "シャ", "くるま"),
    "家": (10, "カ", "いえ"),
    "町": (7, "チョウ", "まち"),
    "国": (8, "コク", "くに"),
    "道": (12, "ドウ", "みち"),
    "空": (8, "クウ", "そら"),
    "雨": (8, "ウ", "あめ"),
    "雪": (11, "セツ", "ゆき"),
    "風": (9, "フウ", "かぜ"),
    "花": (7, "カ", "はな"),
    "木": (4, "モク", "き"),
    "山": (3, "サン", "やま"),
    "川": (3, "セン", "かわ"),
    "海": (9, "カイ", "うみ"),
    "犬": (4, "ケン", "いぬ"),
    "猫": (11, "ビョウ", "ねこ"),
    "何": (7, "カ", "なに"),
    "誰": (15, "スイ", "だれ"),
}


def main() -> None:
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out_dir = os.path.join(root, "assets", "data")
    os.makedirs(out_dir, exist_ok=True)

    words = []
    sentences = {}
    seen = set()
    for order, row in enumerate(WORDS, start=1):
        japanese, kana, romaji, english, pos, sentence, sentence_kana, sentence_en = row
        if japanese in seen:
            raise SystemExit(f"duplicate entry: {japanese}")
        seen.add(japanese)
        words.append({
            "japanese": japanese,
            "kana": kana,
            "romaji": romaji,
            "english": english,
            "partOfSpeech": pos,
            "order": order,
        })
        sentences[japanese] = {
            "japanese": sentence,
            "kana": sentence_kana,
            "english": sentence_en,
        }

    kanji_info = {}
    for japanese, (strokes, on, kun) in KANJI_INFO.items():
        if japanese not in seen:
            raise SystemExit(f"kanji info for a word not in the deck: {japanese}")
        entry = {"strokes": strokes}
        if on != "-":
            entry["on"] = on
        if kun != "-":
            entry["kun"] = kun
        kanji_info[japanese] = entry

    def write(name, payload):
        path = os.path.join(out_dir, name)
        with open(path, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, ensure_ascii=False, indent=2)
            handle.write("\n")
        print(f"wrote {path} ({os.path.getsize(path) / 1024:.1f} KB)")

    write("n5.json", words)
    write("n5_sentences.json", sentences)
    write("n5_kanji_info.json", kanji_info)
    print(f"{len(words)} words, {len(kanji_info)} single-kanji entries")


if __name__ == "__main__":
    main()
